runCDPipelineFront(application: "web-client",
              project: "flow-frontend",
              agent: "nodejs",
              compileCommands: "echo 'registry=https://verdaccio-ff.cablevisionflow.com.ar/\n//verdaccio-ff.cablevisionflow.com.ar/:_authToken=\"ASeidZKU2eOeOo/jMfB7xMlQfedMICWyTb3HziHwdsU=\"' > .npmrc && npm install --verbose verbose && npm run build:stg",
              testCommands: "",
              artifactsDir: "./build",
              applicationTemplate: "./openshift/template.yaml")