spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: test-react
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
      
      