runCIPipelineQuay(application: "test-react",
              project: "test-push-quay-prod",
              agent: "nodejs",
              compileCommands: " npm install && npm run build",
              testCommands: "",
              artifactsDir: "./build",
              applicationTemplate: "./openshift/template.yaml")